# Generated by Django 5.1.7 on 2025-04-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_investment_amount_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('borrower', 'Borrower'), ('investor', 'Investor'), ('admin', 'Admin')], max_length=10),
        ),
    ]
