# Generated by Django 5.1.7 on 2025-03-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(choices=[('Startup Pitch', 'Startup Pitch'), ('Business Growth', 'Business Growth'), ('Education', 'Education'), ('Emergency', 'Emergency'), ('Car Logbook Loan', 'Car Logbook Loan'), ('Nunua/Jenga', 'Nunua/Jenga'), ('Land Financing', 'Land Financing')], max_length=50)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.FloatField(default=12.5)),
                ('repayment_period', models.IntegerField(help_text='Repayment period in months')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Business', 'Business'), ('Personal', 'Personal'), ('Asset Financing', 'Asset Financing')], max_length=50, unique=True)),
            ],
        ),
    ]
