# Generated by Django 5.1.7 on 2025-04-12 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loancategory_main_category_alter_loancategory_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startuppitch',
            name='founder',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancategory',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='StartupPitch',
        ),
    ]
