# Generated by Django 5.1.7 on 2025-04-12 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_startuppitch_founder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('personal', 'Personal'), ('asset', 'Asset Financing')], default='business', max_length=20),
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_officer',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LoanCategory',
        ),
    ]
