# Generated by Django 5.1.7 on 2025-03-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('Health', 'Health'), ('Tech', 'Tech'), ('Agriculture', 'Agriculture'), ('Education', 'Education'), ('Fintech', 'Fintech')], max_length=50)),
                ('amount_deposited', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
